name: CraftBay
main: net.ghostrealms.craftbay.CraftBayPlugin
version: 1.3
authora: [Rmarmorstein, StarTux]
description: CraftBay Auction Plugin Adapted for Ghost Realms
depend: [Vault]
commands:
  auction:
    description: Auction interface
    usage: /<command> - get more information
    aliases: [auc]
    permission: auction.info
  bid:
    description: Shortcut for /auction bid
    usage: /<command> [amount] - bid an amount
    permission: auction.bid
permissions:
  auction.*:
    description: Get all permission nodes
    default: false
    children:
      auction.info: true
      auction.bid: true
      auction.start: true
      auction.admin: true
  auction.info:
    description: Query information about the ongoing auction
    default: true
  auction.bid:
    description: Bid on an auction
    default: true
    children:
      auction.receive: true
  auction.receive:
    description: Receive an item after winning an auction
    default: false
  auction.start:
    description: Start an auction
    default: false
  auction.admin:
    description: Perform administrative commands
    default: op
  auction.nofee:
    description: Player does not have to pay the auction fee
    default: false
  auction.notax:
    description: Player does not have to pay the auction tax
    default: false